### ISSUE TITLE
'Install the following packages before proceeding.' includes things that aren't packages.

### ISSUE THREAD

**Issue by z0rg0n** [parnexcodes/tidal-dl-discord-bot#4]
The instructions include '7zip' as a package to install but when 'apt-get install 7zip' is run it returns the error:
`Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package 7zip
`
If 'pip install 7zip' is run it returns:
`
ERROR: Could not find a version that satisfies the requirement 7zip (from versions: none)
ERROR: No matching distribution found for 7zip
`

The instructions include 'pip install -r requirements.txt' as a package to install. When you run this command it returns the error:
`
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
`

It may be clear what these instructions mean to more experienced users it's unclear to me what is required to enter into the terminal here.

**Comment by parnexcodes** [comment]
run pip install command from source directory.

`sudo apt-get install p7zip-full`
