### ISSUE TITLE
There are multiple places setup step could apply to when editing text file.

### ISSUE THREAD

**Issue by z0rg0n** [parnexcodes/tidal-dl-discord-bot#5]
One of the setup steps says 'Set [database] enabled = true to false.' but there are two places in the text file found with 'rip config --open' might apply.

![image](https://user-images.githubusercontent.com/82673289/143605680-91ce0828-316d-424f-b6a3-8904ecc0b56c.png)

**Comment by parnexcodes** [comment]
database.downloads
