### ISSUE TITLE
not issue but idea

### ISSUE THREAD

**Issue by JOJOVAV** [parnexcodes/tidal-dl-discord-bot#6]
So the bot will see if there is already posted a track/album.
The bot will check link or album and if it's already uploaded then it will post the link to the user instead of redownloading it and posting it. It will save time and reources.

maybe little more info if I wasn't clear [Discord message/conversation](https://discord.com/channels/913269141853601884/913269141853601887/919592024200609873)

**Comment by parnexcodes** [comment]
It's easier on Google drive because of their api. Kraken doesn't provide any , so not possible.
